-- Approvals — Supabase (Postgres) schema
-- Single-signer tool: one fixed profile row, a managed project list, and invoices
-- that move from 'pending' (loaded, not yet signed) to 'approved' (stamped).
--
-- IDs are generated by the application (crypto.randomUUID()), not the database.
-- RLS is enabled with no policies on every table: the anon/publishable key can
-- read or write nothing. The app talks to Postgres exclusively via the
-- service_role key from the server, which bypasses RLS — this is defense in
-- depth in case the publishable key is ever exposed client-side.

create table if not exists profile (
  id text primary key default 'default',
  full_name text not null default 'TG Mthembu',
  signature_path text
);

alter table profile enable row level security;

insert into profile (id, full_name)
values ('default', 'TG Mthembu')
on conflict (id) do nothing;

create table if not exists projects (
  id text primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

alter table projects enable row level security;

create table if not exists invoices (
  id text primary key,
  project text not null,
  approved_by text not null,
  approved_date text not null,
  item_description text,
  original_file_path text not null,
  stamped_file_path text,
  status text not null default 'approved',
  created_at timestamptz not null default now()
);

alter table invoices enable row level security;

create table if not exists price_checks (
  id text primary key,
  invoice_id text references invoices (id) on delete cascade,
  product text not null,
  location text not null default 'Johannesburg',
  results jsonb not null,
  ai_insight text not null,
  is_mock boolean not null default true,
  created_at timestamptz not null default now()
);

alter table price_checks enable row level security;

-- Storage buckets `signatures` and `invoices` are created via the dashboard
-- (already done) — no bucket-level policies needed since only the
-- service_role key (server-side) touches Storage.
